apiVersion: v1
kind: Service
metadata:
  name: random-quote-service
  labels:
    name: random-quote-service
    app: demo-random-quote-deployment
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     name: random-quote-service
     app: demo-random-quote-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-quote-deployment
  labels:
    app: demo-random-quote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: random-quote-deployment
      app: demo-random-quote-deployment
  template:
    metadata:
      name: random-quote-deployment
      labels:
        name: random-quote-deployment
        app: demo-random-quote-deployment

    spec:
      containers:
      - name: random-quote-deployment
        image: gcr.io/parabolic-rope-278721/random-quote
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ramdom-quote-deployment
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ramdom-quote-deployment
  targetCPUUtilizationPercentage: 80

